package com.toptal;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;


public class RecordedTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/opt/WebDriver/bin/geckodriver");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void recorded() {
    driver.get("https://www.toptal.com/");
    driver.manage().window().maximize();
    driver.findElement(By.linkText("Apply as a Freelancer")).click();
    driver.findElement(By.id("talent_create_applicant_full_name")).click();
    driver.findElement(By.id("talent_create_applicant_full_name")).sendKeys("Didi");
    driver.findElement(By.id("talent_create_applicant_email")).click();
    driver.findElement(By.id("talent_create_applicant_email")).sendKeys("dddd@mail.com");
    driver.findElement(By.id("talent_create_applicant_password")).sendKeys("dddd1234");
    driver.findElement(By.id("talent_create_applicant_password_confirmation")).sendKeys("dddd1234");
  }
}
